//Generic Dimension


// ignore_for_file: constant_identifier_names

const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2x = 16.0;
const MARGIN_MEDIUM_3x = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2x = 16.0;
const TEXT_REGULAR_3x = 20.0;
const TEXT_HEADING = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_BIG = 32.0;

//App Specific
const WELCOMEPAGE_IMAGE_HEIGHT = 250.0;
const HOMEPAGE_SEARCH_ICON_SIZE = 35.0;
const LONG_BUTTON_HEIGHT = 60.0;
const HORIZONTAL_MOVIE_LIST_HEIGHT = 330.0;
const HORIZONTAL_MOVIE_LIST_ITEM_WIDTH = 180.0;
const HORIZONTAL_MOVIE_LIST_IMAGE_HEIGHT = 60.0;
const SLIVER_APP_BAR_HEIGHT = 300.0;
const HORIZONTAL_MOVIE_GENRE_TEXT_SIZE = 10.0;
const BACK_BUTTON_SIZE = 40.0;
const CLOSE_BUTTON_ICON_SIZE = 25.0;
const SEAT_TEXT_SIZE = 6.0;

const SPACE_FOR_FLOATING_LONG_BUTTON = MARGIN_XLARGE + LONG_BUTTON_HEIGHT + MARGIN_MEDIUM_3x;

const COUNTER_WIDTH = 100.0;
const COUNTER_HEIGHT = 30.0;
const COUNTER_HORIZONTAL_PADDING = 10.0;

const CREDIT_CARD_HEIGHT = 200.0;


const TICKET_PAGE_IMAGE_HEIGHT = 180.0;
const TICKET_PAGE_MOVIE_IMAGE_AND_INFO_HEIGHT = TICKET_PAGE_IMAGE_HEIGHT + 70.0;
const TICKET_SEPARATOR_HEIGHT = 30.0;

const DRAWER_GMAIL_FONT_SIZE = 12.0;

const DETAILS_SCREEN_PLAY_BUTTON_SIZE = 60.0;
const DETAILS_CAST_HEIGHT = 75.0;

const BUTTON_BORDER_RADIUS = 10.0;

const RATINGBAR_ITEM_SIZE = 25.0;

const PICK_DATE_HEIGHT = 120.0;