//TypeID
// ignore_for_file: constant_identifier_names

const int HIVE_TYPE_ID_PROFILE_VO = 1;
const int HIVE_TYPE_ID_CARD_VO = 2;
const int HIVE_TYPE_ID_ACTOR_VO = 3;
const int HIVE_TYPE_ID_COLLECTION_VO = 4;
const int HIVE_TYPE_ID_COUNTRY_VO = 5;
const int HIVE_TYPE_ID_DATE_VO = 6;
const int HIVE_TYPE_ID_MOVIE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 9;
const int HIVE_TYPE_ID_GENRE_VO = 10;
const int HIVE_TYPE_ID_TIMESLOTS_VO = 11;
const int HIVE_TYPE_ID_CINEMA_VO = 12;
const int HIVE_TYPE_ID_SNACK_VO = 13;
const int HIVE_TYPE_ID_PAYMENT_METHOD_VO = 14;
const int HIVE_TYPE_ID_CINEMA_LIST_VO = 15;


//BoxName
const String BOX_NAME_PROFILE_VO = 'BOX_NAME_PROFILE_VO';
const String BOX_NAME_ACTOR_VO = 'BOX_NAME_ACTOR_VO';
const String BOX_NAME_MOVIE_VO = 'BOX_NAME_MOVIE_VO';
const String BOX_NAME_GENRE_VO = 'BOX_NAME_GENRE_VO';
const String BOX_NAME_CINEMA_VO = 'BOX_NAME_CINEMA_VO';
const String BOX_NAME_SNACK_VO = 'BOX_NAME_SNACK_VO';
const String BOX_NAME_PAYMENT_METHOD_VO = 'BOX_NAME_PAYMENT_METHOD_VO';
const String BOX_NAME_CINEMA_LIST_VO = 'BOX_NAME_CINEMA_LIST_VO';